DROP DATABASE IF EXISTS oilreps;
CREATE DATABASE oilreps;
CREATE ROLE oiluser LOGIN;
ALTER ROLE oiluser WITH PASSWORD 'oil';
ALTER ROLE oiluser WITH PASSWORD 'oil';
GRANT ALL ON ALL TABLES IN SCHEMA public TO oiluser;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO oiluser;
